email: ...
full_name: Johan Van Campenhout
name: Johan
background: Johan is the owner of JVC & Co bvba, a Belgian company specializing in heating and plumbing services. The company provides central heating and sanitary installations, with expertise in thermal solar energy systems.
schedule_preferences: By default, work hours are Monday to Saturday, 9:00 AM to 7:00 PM, with service areas in Brussels, Antwerp, Ghent and surroundings.
background_preferences: |
  As a sole proprietor specializing in heating and plumbing services, all technical queries and service requests should be handled directly and promptly. Focus on maintenance, repairs, and installations in the Brussels, Antwerp, and Ghent areas.
response_preferences:
timezone: "CET"
rewrite_preferences: |
  Johan has a few rules for how he likes his emails to be written:

  - Always maintain a formal and professional tone in all communications
  - Match the language of the customer (Dutch, French, or English)
  - Include proper formal greeting and sign-off ("Met vriendelijke groeten,")
  - Be clear and specific about scheduling details and technical requirements
  - When writing in Dutch, use formal "u" instead of informal "jij"

triage_no: |
  - Automated marketing emails and newsletters
  - Cold outreach from vendors selling equipment or services
  - General promotional materials
  - Social media notifications
  - Non-business related emails
  - Automated calendar invitations

triage_notify: |
  - Any urgent maintenance or repair requests from customers
  - Requests for quotes or estimates
  - Technical questions about heating systems or installations
  - Warranty-related inquiries
  - Supply chain or parts availability updates that might affect customer service
  - Emergency service requests outside normal hours

triage_email: |
  - All customer inquiries about maintenance, repairs, or installations
  - Emergency service requests
  - Quote requests for new installations or major repairs
  - Follow-up emails from existing customers
  - Technical queries about heating systems
  - Scheduling requests for maintenance or repairs
  - Emails about parts or equipment availability
  - Customer feedback or concerns
  - Any email that requires technical expertise or scheduling of on-site work
  - Emails where customers are trying to schedule maintenance or repairs

  Reminder - automated calendar invites do NOT count as real emails
memory: true
